Repository doc88git/flux-style-guide, pull requests merged in 2020-03, with the labels that each got.

#82 WIP: Reference documents and guidelines for contributors
  .editorconfig
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/en/CODE_OF_CONDUCT.md
  .github/en/COMMIT_CONVENTION.md
  .github/en/CONTRIBUTING.md
  .github/pt-br/CODE_OF_CONDUCT.md
  .github/pt-br/COMMIT_CONVENTION.md
  .github/pt-br/CONTRIBUTING.md
  .gitignore
  .vscode/settings.json
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/components/FDatepicker/stories/f-datepicker.stories.js
  src/components/FDisplay/FDisplay.vue
  src/components/FLayout/stories/f-layout.stories.js
  src/components/FMenu/stories/f-menu.stories.js
  src/components/FModal/index.js
  src/components/FPagination/FPagination.spec.js
  src/components/FPagination/__snapshots__/FPagination.spec.js.snap
  src/components/FSeparator/index.js
  src/components/FTag/FTag.spec.js
  src/components/FTag/__snapshots__/FTag.spec.js.snap
  src/components/FTagGroup/index.js
  src/components/FTagGroup/stories/f-tag-group.stories.js
  src/components/FTitle/index.js
  src/components/FTitle/stories/f-title-stories.js
  src/components/FToggle/FToggle.vue
  src/components/FToggle/index.js
  src/components/FUpload/FUpload.vue
  src/components/FUpload/index.js
  src/components/FUpload/stories/f-upload.stories.js
  yarn.lock
Labels: documentation

#97 Fix/dropdown
  package.json
  src/components/FDropdown/FDropdown.vue
Labels: bug

#99 FDisplayPerPage - Corrige chamada da função change no evento click (Issue #96)
  src/components/FDisplayPerPage/FDisplayPerPage.vue
Labels: bug

#98 FPagination - Correção do calculo de paginas a serem renderizadas #95
  src/components/FPagination/FPagination.vue
Labels: bug

#94 FMenu - Correção de tamanho dos items e sub-items
  src/components/FMenu/FMenu.vue
  src/components/FMenu/FMenuItem.vue
  src/components/FMenu/FMenuList.vue
Labels: bug

#93 Fix input with decimal value
  src/components/FField/FInputType.vue
  src/components/FField/stories/f-field.stories.js
Labels: bug

#92 Use flux-icon as default lib in f-buttons
  src/components/FButton/FButton.vue
Labels: enhancement

#102 FPagination - Corrige falta de sincronia do estado local com a prop currentPage
  src/components/FPagination/FPagination.spec.js
  src/components/FPagination/FPagination.vue
Labels: bug

#105 FTooltip - Implementa posicionamento fixo (Issue #89)
  src/components/FMenu/FMenuItem.vue
  src/components/FMenu/FMenuList.vue
  src/components/FTooltip/FTooltip.vue
Labels: bug

#112 FPagination - Hotfix de bug de renderização de paginação
  src/components/FPagination/FPagination.vue
Labels: bug

#111 Update Flux-Icons
  package-lock.json
  package.json
  src/components/FIcon/FIcon.vue
  yarn.lock
Labels: enhancement

#110 Implementa componente FAccordion
  src/components/FAccordion/FAccordion.spec.js
  src/components/FAccordion/FAccordion.vue
  src/components/FAccordion/__snapshots__/FAccordion.spec.js.snap
  src/components/FAccordion/index.js
  src/components/FAccordion/stories/f-accordion-stories.js
  src/components/index.js
Labels: enhancement
